apiVersion: apps/v1
kind: Deployment
metadata:
    name: gunicorn
spec:
    selector:
        matchLabels:
            app: gunicorn
    template:
        metadata:
            labels:
                app: gunicorn
        spec:
            containers:
                - name: gunicorn
                  image: francescorisso/dashboard_casa_gunicorn:latest
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 8000
                  volumeMounts:
                      - mountPath: /server/SQLsettings
                        name: sql-settings
                      - mountPath: /server/schedules
                        name: schedules
                  env:
                      - name: SQL_dialect
                        value: "..."
                      - name: SQL_username
                        value: "..."
                      - name: SQL_password
                        value: "..."
                      - name: SQL_host
                        value: "..."
                      - name: SQL_dbname
                        value: "..."
                      - name: CMI_username
                        value: "..."
                      - name: CMI_password
                        value: "..."
            volumes:
                - name: sql-settings
                  persistentVolumeClaim:
                      claimName: dashobard-casa-gunicorn-settings
                - name: schedules
                  persistentVolumeClaim:
                      claimName: dashobard-casa-gunicorn-schedules

---
apiVersion: v1
kind: Service
metadata:
    name: gunicorn
spec:
    type: ClusterIP
    selector:
        app: gunicorn
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
