apiVersion: apps/v1
kind: Deployment
metadata:
    name: webserver
spec:
    selector:
        matchLabels:
            app: webserver
    template:
        metadata:
            labels:
                app: webserver
        spec:
            containers:
                - name: webserver
                  image: francescorisso/dashboard_casa_nginx:latest
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 80
                  env:
                      - name: SSL_key
                        value: "..."
                      - name: SSL_pem
                        value: "..."

---
apiVersion: v1
kind: Service
metadata:
    name: webserver
spec:
    type: NodePort
    selector:
        app: webserver
    ports:
        - protocol: TCP
          port: 8001
          targetPort: 80
