apiVersion: v1
kind: PersistentVolume
metadata:
    name: dashobard-casa-gunicorn-settings
spec:
    capacity:
        storage: 5Ki
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: manual
    hostPath:
      path: "/mnt/dashboard-casa/gunicorn-settings"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: dashobard-casa-gunicorn-settings
spec:
    storageClassName: manual
    resources:
        requests:
            storage: 5Ki
    accessModes:
        - ReadWriteOnce
