name: build docker containers and push to Dockerhub

on:
    workflow_run:
        workflows: ["React build and commit to build branch"]
        types:
            - completed

jobs:
    dockerNginx:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./nginx.Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dashboard_casa_nginx:latest

    gunicornNginx:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./gunicorn.Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dashboard_casa_gunicorn:latest
